### PR TITLE
WIP: `_update_by_query` support

### PR DESCRIPTION
**Pull request by marshall007**
@voldern I wanted to get your thoughts on this before putting any more work into it. As a first pass, I've implemented this as a separate Writable stream, but it would probably be more convenient to use if it were behind a new `action` type (perhaps `update_by_query`?) on the existing Writable class.

Note that I don't think there's a real use-case in buffering "update by query" requests since it is already a bulk operation in itself. So if we implemented this on the existing Writable class, I think we would just want to immediately flush `update_by_query` actions instead of queuing them with the other operations.

Let me know what you think.

For reference: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-update-by-query.html

### CODE REVIEW

**Comment by marshall007** [comment]
I have the `update_by_query` action working within the existing Writable class in this commit on another branch (https://github.com/marshall007/elasticsearch-bulk-index-stream/commit/bff3de2a75c87df8b9430b961bef1400ba2915ee) if you're interested to see what that looks like.

**Comment by marshall007** [comment]
@voldern ping. I've been using this branch over the past couple weeks and it works well. Let me know if you plan on integrating this feature and I'll add some tests.

**Comment by voldern** [comment]
@marshall007 Once again, thank you for contributing! :bow:

I'm sorry for not getting back to you sooner, I've been away traveling. I'm going to give you a response later today or tomorrow.

**Comment by voldern** [comment]
I think it should live in the same Writable class, for me it feels like a simpler solution so that you don't have to deal with different objects.

I agree that there is no use for buffering, since `update_by_query` is not supported by the bulk API.

I will merge this as soon as the tests are added.

PS: When this is merged I might have to come up with a new name for the package, since its no longer just a bulk-index stream. It can do deletes and `update_by_action` as well. Any suggestions? :)

**Comment by marshall007** [comment]
@voldern just wrote some tests, so I think we're good to go here.

In regards to the rename, I was thinking the same thing, actually. Perhaps something like `elasticsearch-sync-stream` with a description like:

> A writable stream for keeping your data synchronized in Elasticsearch. Supports virtually all indexing operations including `index`, `update`, `update_by_query`, and `delete`.

However, with a package name like that, I'm not sure if people would assume this package is opinionated in some way or that it provides some sort of framework for synchronization (in other words that it does more than they want it to).

**Comment by voldern** [comment]
Merged. :bow:

What do you think about `elasticsearch-writable-stream` ? There are other packages with similar names, but that one isn't taken. As you point out, `elasticsearch-sync-stream` might imply that it does more.

**Comment by voldern** [comment]
Once we land the name, I'll create a new package incorporating these changes, and deprecate the current package with a warning to change the name.

**Comment by marshall007** [comment]
@voldern awesome, thanks! I can't think of anything better, so `elasticsearch-writable-stream` sounds good to me!

**Comment by voldern** [comment]
@marshall007 The package has been renamed to [elasticsearch-writable-stream](https://github.com/voldern/elasticsearch-writable-stream) and v2.0.0 includes your changes.

**Pull request merged**
